import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/landing_page/Navbar";

export const metadata: Metadata = {
  title: "Tixly",
  description: "Generated by create next app",
};

export default function Main({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <Navbar />
      {children}
    </section>
  );
}
