import type { Metadata } from "next";
import AuthNavbar from "@/components/auth/AuthNavbar";

export const metadata: Metadata = {
  title: "Tixly",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="flex flex-col">
      <AuthNavbar />
      <div className="flex-1">{children}</div>
    </section>
  );
}
