import AuthNavbar from "@/components/Auth/AuthNavbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tixly",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <AuthNavbar />
      {children}
    </section>
  );
}
